default: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: cefs1984
  password: flartoolkit
  host: localhost

development:
  <<: *defaults
  database: exemplo_activerecord_development

test:
  <<: *defaults
  database: exemplo_activerecord_test

production:
  <<: *defaults
  database: exemplo_activerecord_production
